- paged:
    queryParameters:
      page:
        description: The page number
        default: 0
        type: number
      size:
        description: The page size
        default: 50
        type: number